# Generated by Django 3.0.8 on 2020-08-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('alerternatEmail', models.EmailField(max_length=254, null=True)),
                ('isVerified', models.BooleanField(default=0)),
                ('profilePic', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
