# Generated by Django 3.0.8 on 2020-08-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='alerternatEmail',
            new_name='alerternateEmail',
        ),
    ]
