# Generated by Django 3.0.8 on 2020-08-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200806_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='alerternateEmail',
            new_name='alternateEmail',
        ),
    ]
