# Generated by Django 3.0.8 on 2020-08-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globaltables', '0002_auto_20200731_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardId', models.AutoField(primary_key=True, serialize=False)),
                ('boardTitle', models.CharField(max_length=50)),
                ('boardDescription', models.CharField(max_length=1000)),
                ('boardImage', models.CharField(max_length=1000)),
                ('createdOn', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=0)),
                ('boardType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globaltables.BoardType')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
