# Generated by Django 3.0.8 on 2020-08-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globaltables', '0002_auto_20200731_1158'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMemberStatus',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='boardImage',
        ),
        migrations.AddField(
            model_name='board',
            name='token',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.CreateModel(
            name='BoardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedOn', models.DateTimeField()),
                ('boardId', models.ManyToManyField(to='board.Board')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaltables.Role')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.BoardMemberStatus')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
