# Generated by Django 3.0.8 on 2020-08-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globaltables', '0005_accessrights'),
        ('board', '0003_auto_20200813_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmembers',
            name='roleId',
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='roleId',
            field=models.ManyToManyField(to='globaltables.Role'),
        ),
        migrations.CreateModel(
            name='BoardMembersAccessRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessRight', models.ManyToManyField(to='globaltables.AccessRights')),
                ('boardMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BoardMembers')),
            ],
        ),
    ]
