# Generated by Django 3.0.8 on 2020-08-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globaltables', '0005_accessrights'),
        ('board', '0004_auto_20200815_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmembers',
            name='roleId',
        ),
        migrations.RemoveField(
            model_name='boardmembers',
            name='statusId',
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='isMuted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='isRemoved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='globaltables.Role'),
        ),
        migrations.DeleteModel(
            name='BoardMemberStatus',
        ),
    ]
