# Generated by Django 3.0.8 on 2020-07-31 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('boardTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('boardType', models.CharField(max_length=50, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('boardTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globaltables.BoardType')),
            ],
        ),
    ]
