# Generated by Django 3.0.8 on 2020-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaltables', '0002_auto_20200731_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtype',
            name='boardTypeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
