# Generated by Django 3.0.8 on 2020-08-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globaltables', '0003_auto_20200813_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globaltables.BoardType')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globaltables.Role')),
            ],
        ),
    ]
